apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-04-13T19:57:51Z"
  labels:
    app: puppet
  name: puppet
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - ./puppetmaster
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: HOSTNAME
      value: puppet
    image: localhost:5000/puppetmaster:latest
    name: puppet
    ports:
    - containerPort: 8140
      hostPort: 8140
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    tty: true
    workingDir: /home/root/puppetmaster
status: {}

